project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_TOKEN


files: [
  {
    "source": "/src/Localization/en_US-gog-oss.xaml",
    "translation": "/src/Localization/%locale_with_underscore%-gog-oss.xaml",
    "escape_quotes": 3,
    "escape_special_characters": 0,
  }
]
