project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_TOKEN


files: [
  {
    "source": "/src/Localization/en-US/gog-oss.ftl",
    "translation": "/src/Localization/%locale%/gog-oss.ftl",
    "escape_quotes": 3,
    "escape_special_characters": 0,
  }
]
