gog-oss-use-vertical-covers = Use vertical covers
gog-oss-language = Language
gog-oss-beta-channel = Beta channel
gog-oss-game-not-installable = { $gameTitle } doesn't appear to be installable. Check downloadable content at { $url }.
gog-oss-enable-comet-support = Enable Comet support
gog-oss-enable-comet-support-tool-tip = It's required for achievements, leaderboards and multiplayer mode, but may cause problems with operation of some games.
gog-oss-manage-extras = Manage extras
gog-oss-no-available-extras = No available extras.
gog-oss-notify-about = Notify when:
gog-oss-notify-new-message = someone sends a new message
gog-oss-notify-friend-invite = someone sends a friend invitation
gog-oss-notify-game-invite = someone sends invitation to a game
gog-oss-notify-friend-online = a friend comes online
gog-oss-notify-friend-starts-game = a friend starts a game
gog-oss-notify-sound = Play sound for notifications
gog-oss-notification-volume = Sounds volume
gog-oss-notification-position = Position of notifications
gog-oss-top-left = Top left
gog-oss-top-right = Top right
gog-oss-bottom-left = Bottom left
gog-oss-bottom-right = Bottom right
gog-oss-enable-overlay = Enable Galaxy Overlay
