gog-oss-comet-custom-path = Comet Path
gog-oss-comet-version = Comet version
gog-oss-comet-binary = Comet binary
gog-oss-gogdl-custom-path = Gogdl Path
gog-oss-gogdl-version = Gogdl version
gog-oss-gogdl-binary = Gogdl binary
gog-oss-use-vertical-covers = Use vertical covers
gog-oss-language = Language
gog-oss-beta-channel = Beta channel
gog-oss-game-not-installable = { $gameTitle } doesn't appear to be installable. Check downloadable content at { $url }.
gog-oss-enable-comet-support = Enable Comet support
gog-oss-enable-comet-support-tool-tip = It's required for achievements, leaderboards and multiplayer mode, but may cause problems with operation of some games.
gog-oss-comet-update-policy = Check for Comet and Gogdl updates
