gog-oss-use-vertical-covers = Używaj okładek pionowych
gog-oss-language = Język
gog-oss-beta-channel = Kanał beta
gog-oss-game-not-installable = Wydaje się, że { $gameTitle } nie jest możliwy do zainstalowania. Sprawdź zawartość do pobrania na { $url }.
gog-oss-enable-comet-support = Włącz obsługę Comet
gog-oss-enable-comet-support-tool-tip = Jest to wymagane dla osiągnięć, tablic wyników i trybu wieloosobowego, ale może powodować problemy z działaniem niektórych gier.
gog-oss-manage-extras = Zarządzaj bonusami
gog-oss-no-available-extras = Brak dostępnych bonusów.
gog-oss-notify-about = Powiadom, gdy:
gog-oss-notify-new-message = ktoś wyśle nową wiadomość
gog-oss-notify-friend-invite = ktoś wyśle zaproszenie do znajomych
gog-oss-notify-game-invite = ktoś wyśle zaproszenie do gry
gog-oss-notify-friend-online = przyjaciel będzie online
gog-oss-notify-friend-starts-game = przyjaciel rozpocznie grę
gog-oss-notify-sound = Odtwarzaj dźwięk dla powiadomień
gog-oss-notification-volume = Głośność dźwięku
gog-oss-notification-position = Pozycja powiadomień
gog-oss-top-left = Lewy górny róg
gog-oss-top-right = Prawy górny róg
gog-oss-bottom-left = Lewy dolny róg
gog-oss-bottom-right = Prawy dolny róg
gog-oss-enable-overlay = Włącz nakładkę Galaxy
