gog-oss-use-vertical-covers = Используйте вертикальные обложки
gog-oss-language = Язык
gog-oss-beta-channel = Бета канал
gog-oss-game-not-installable = { $gameTitle } не может быть установлен. Проверьте скачиваемое содержимое на { $url }.
gog-oss-enable-comet-support = Включить поддержку кометы
gog-oss-enable-comet-support-tool-tip = Это необходимо для достижений, таблиц лидеров и многопользовательского режима, но может вызвать проблемы с работой некоторых игр.
gog-oss-manage-extras = Управление дополнениями
gog-oss-no-available-extras = Нет доступных дополнений.
gog-oss-notify-about = Уведомлять когда:
gog-oss-notify-new-message = кто-то посылает новое сообщение
gog-oss-notify-friend-invite = кто-то отправляет приглашение в друзья
gog-oss-notify-game-invite = кто-то отправляет приглашение в игру
gog-oss-notify-friend-online = когда друг подключается к сети
gog-oss-notify-friend-starts-game = когда друг заходит в игру
gog-oss-notify-achievement-unlock = достижение разблокировано
gog-oss-notify-sound = Включите звук для уведомлений
gog-oss-notification-volume = Громкость Звука
gog-oss-notification-position = Расположение уведомлений
gog-oss-top-left = Вверху слева
gog-oss-top-right = Вверху справа
gog-oss-bottom-left = Внизу слева
gog-oss-bottom-right = Внизу справа
gog-oss-enable-overlay = Включить оверлей Galaxy
