gog-oss-comet-custom-path = Путь к Comet
gog-oss-comet-version = Версия Comet
gog-oss-comet-binary = Бинарная Comet
gog-oss-gogdl-custom-path = Путь к Gogdl
gog-oss-gogdl-version = Версия Gogdl
gog-oss-gogdl-binary = Бинарная Gogdl
gog-oss-use-vertical-covers = Используйте вертикальные обложки
gog-oss-language = Язык
gog-oss-beta-channel = Бета канал
gog-oss-game-not-installable = { $gameTitle } не может быть установлен. Проверьте скачиваемое содержимое на { $url }.
gog-oss-enable-comet-support = Включить поддержку кометы
gog-oss-enable-comet-support-tool-tip = Это необходимо для достижений, таблиц лидеров и многопользовательского режима, но может вызвать проблемы с работой некоторых игр.
gog-oss-comet-update-policy = Проверьте обновления Comet и Gogdl
