gog-oss-use-vertical-covers = 縦長カバーを使用
gog-oss-language = 言語
gog-oss-beta-channel = ベータチャンネル
gog-oss-game-not-installable = { $gameTitle } はインストール可能ではないようです。{ $url } でダウンロード可能なコンテンツを確認してください。
gog-oss-enable-comet-support = Comet サポートを有効化
gog-oss-enable-comet-support-tool-tip = 実績、リーダーボード、マルチプレイヤーモードに必要ですが、一部のゲームの動作に問題が発生する可能性があります。
gog-oss-manage-extras = 追加コンテンツを管理
gog-oss-no-available-extras = 利用可能な追加コンテンツはありません。
gog-oss-notify-about = 通知するタイミング：
gog-oss-notify-new-message = 誰かが新しいメッセージを送信したとき
gog-oss-notify-friend-invite = 誰かがフレンド招待を送信したとき
gog-oss-notify-game-invite = 誰かがゲームへの招待を送信したとき
gog-oss-notify-friend-online = フレンドがオンラインになったとき
gog-oss-notify-friend-starts-game = フレンドがゲームを開始したとき
gog-oss-notify-achievement-unlock = 実績が解除されたとき
gog-oss-notify-sound = 通知音を再生
gog-oss-notification-volume = 通知音の音量
gog-oss-notification-position = 通知の位置
gog-oss-top-left = 左上
gog-oss-top-right = 右上
gog-oss-bottom-left = 左下
gog-oss-bottom-right = 右下
gog-oss-enable-overlay = Galaxy オーバーレイを有効化
gog-oss-import-hidden-games = 非表示のゲームをインポート
gog-oss-cdn-order = CDN の順序
gog-oss-show-all-cdns = すべての CDN を表示
gog-oss-game = ゲーム
