gog-oss-comet-custom-path = Ruta de Comet
gog-oss-comet-version = Versión de Comet
gog-oss-comet-binary = Binario de Comet
gog-oss-gogdl-custom-path = Ruta de Gogdl
gog-oss-gogdl-version = Versión de Gogdl
gog-oss-gogdl-binary = Binario de Gogdl
gog-oss-use-vertical-covers = Usar cubiertas verticales
gog-oss-language = Idioma
gog-oss-beta-channel = Canal beta
gog-oss-game-not-installable = { $gameTitle } no parece ser instalable. Comprueba el contenido descargable en { $url }.
gog-oss-enable-comet-support = Habilitar soporte de Comet
gog-oss-enable-comet-support-tool-tip = Es necesario para logros, tablas de clasificación y modo multijugador, pero puede causar problemas con el funcionamiento de algunos juegos.
gog-oss-comet-update-policy = Buscar actualizaciones de Comet y Gogdl
