gog-oss-use-vertical-covers = 使用纵向封面
gog-oss-language = 语言
gog-oss-beta-channel = Beta 通道
gog-oss-game-not-installable = { $gameTitle } 似乎没有安装。请在 { $url } 上检查可下载的内容。
gog-oss-enable-comet-support = 启用 Comet 支持
gog-oss-enable-comet-support-tool-tip = 它是成就、排行榜和多人游戏模式所必需的，但可能会导致某些游戏的运行问题。
gog-oss-manage-extras = 管理扩展
gog-oss-no-available-extras = 没有可用的扩展。
gog-oss-notify-about = 通知时机：
gog-oss-notify-new-message = 收到新消息
gog-oss-notify-friend-invite = 收到好友伸请
gog-oss-notify-game-invite = 收到游戏邀请
gog-oss-notify-friend-online = 朋友上线
gog-oss-notify-friend-starts-game = 朋友开始游戏
gog-oss-notify-sound = 播放提示音
gog-oss-notification-volume = 提示音音量
gog-oss-notification-position = 通知的位置
gog-oss-top-left = 左上角
gog-oss-top-right = 右上角
gog-oss-bottom-left = 左下角
gog-oss-bottom-right = 右下角
gog-oss-enable-overlay = 启用 GOG叠加层
